-- =====================================================
-- Add Super Admin: neezykidngoni@gmail.com
-- =====================================================
-- This SQL script adds neezykidngoni@gmail.com as a super admin
-- Run this in your Supabase SQL Editor at: https://supabase.com/dashboard/project/_/sql
--
-- Password: Ngoni2003
-- Role: super_admin
-- =====================================================

-- Function to hash password using PBKDF2 (same as AdminAuthService)
-- Note: This creates a simplified hash. For production, use the Python script
-- which properly implements PBKDF2 with 100,000 iterations

-- First, check if admin already exists
DO $$
DECLARE
    existing_admin_id INTEGER;
    password_hash TEXT;
    password_salt TEXT;
BEGIN
    -- Check if admin exists
    SELECT id INTO existing_admin_id
    FROM admin_users
    WHERE email = 'neezykidngoni@gmail.com';
    
    IF existing_admin_id IS NOT NULL THEN
        -- Update existing admin
        -- Note: We'll use a temporary hash here. The actual hash should be generated by Python
        -- For now, we'll use a placeholder that will need to be updated
        
        -- Generate salt
        password_salt := encode(gen_random_bytes(32), 'hex');
        
        -- Create a simplified hash (you should replace this with actual PBKDF2 hash)
        -- The proper hash can be generated by running the Python script
        password_hash := encode(digest('Ngoni2003' || password_salt, 'sha256'), 'hex');
        
        UPDATE admin_users
        SET 
            password_hash = password_hash,
            password_salt = password_salt,
            role = 'super_admin',
            is_active = TRUE,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = existing_admin_id;
        
        RAISE NOTICE 'Updated existing admin user with ID: %', existing_admin_id;
    ELSE
        -- Insert new admin
        -- Generate salt
        password_salt := encode(gen_random_bytes(32), 'hex');
        
        -- Create a simplified hash (you should replace this with actual PBKDF2 hash)
        password_hash := encode(digest('Ngoni2003' || password_salt, 'sha256'), 'hex');
        
        INSERT INTO admin_users (
            email,
            password_hash,
            password_salt,
            first_name,
            last_name,
            role,
            is_active,
            created_at,
            updated_at
        ) VALUES (
            'neezykidngoni@gmail.com',
            password_hash,
            password_salt,
            'Ngonidzashe',
            'Zimbwa',
            'super_admin',
            TRUE,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        );
        
        RAISE NOTICE 'Inserted new super admin user';
    END IF;
END $$;

-- Verify the admin was created/updated
SELECT 
    id,
    email,
    first_name || ' ' || last_name AS full_name,
    role,
    is_active,
    created_at,
    last_login
FROM admin_users
WHERE email = 'neezykidngoni@gmail.com';

-- List all admin users
SELECT 
    id,
    email,
    first_name || ' ' || last_name AS full_name,
    role,
    is_active,
    created_at
FROM admin_users
ORDER BY created_at;
